name: "Upload nix store info"
runs:
  using: "composite"
  steps:
  - name: Output to file
    run: nix path-info --all --sigs --size > nix-path-info.txt
    shell: bash
  - name: Print summary
    run: cat nix-path-info.txt | fgrep ultimate | awk '{print $2}' | awk '{s+=$1} END {printf "%.0f\n", s}' | numfmt --to=iec
    shell: bash
  - name: 'Upload nix-path-info'
    uses: actions/upload-artifact@v4
    with:
      name: nix-path-info
      path: nix-path-info.txt
      retention-days: 5
