name: "Test"
on:
  pull_request:
  push:
jobs:
  controller-wifi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prep-build-env
    - run: NIXPKGS_ALLOW_UNFREE=1 ./run-controller-wifi-many-times.sh 20
